name: mat-sim

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy>=1.12
  - matplotlib
  - sqlite
  - pip
  - pip:
      - pymatgen
      - mp-api
      - ase
      - mace-torch
      - chgnet
      - python-dotenv
      - PyMieScatt
